defaults:
  - default
  - _self_

trainer:
  train_dataloader:
  dataset:
      _target_: src.core.datasets.C4Dataset
      sequence_length: ${common.sequence_length}
      tokenize_fn: ???
      path: ${cluster_switch.train_path_c4}
      split: train
      seed: 123
      use_new_sampling_method: true
      shuffle: true
      world_size_independent: false
    num_workers: 8

  eval_dataloader:
    dataset:
      _target_: src.core.datasets.C4Dataset
      sequence_length: ${common.sequence_length}
      tokenize_fn: ???
      path: ${cluster_switch.eval_path_c4}
      split: validation
      seed: 123
      use_new_sampling_method: true
      shuffle: true
      world_size_independent: false
    num_workers: 8