defaults:
  - default
  - _self_

trainer:
  train_dataloader:
    datasets:
      ${cluster_switch.train_path_c4}: 1.0
    dataset_split: train
    num_workers: 8

  eval_dataloader:
    datasets:
      ${cluster_switch.eval_path_c4}: 1.0
    dataset_split: validation
    num_workers: 8