common:
  data_seed: 123

trainer:
  train_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset: ???
    total_batch_size: ${common.batch_size}
    num_workers: ???

  eval_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset: ???
    total_batch_size: ${common.batch_size}
    num_workers: ???