[workspace]
authors = ["Janek <jan.malasnicki@gmail.com>"]
channels = ["conda-forge"]
name = "nano"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]   # drop osx-64 (Intel Mac)
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12.3"

[pypi-dependencies]
transformers = "==4.55.0"
datasets = "==3.1.0"
neptune = "==1.13.0"
submitit = "==1.5.2"
hydra-core = "==1.3.2"
hydra-submitit-launcher = "==1.2.0"
fabric = "==3.2.2"
pydantic = "==2.10.4"
torchdata = "==0.11.0"
black = "==25.1.0"
torchao = "==0.11.0"
torchtune = "==0.6.1"
lm-eval = ">=0.4.0"

[target.linux-64.pypi-dependencies]
torch = { version = "==2.7.1", index = "https://download.pytorch.org/whl/cu128" }

[target.linux-aarch64.pypi-dependencies]
torch = { version = "==2.6", index = "https://download.pytorch.org/whl/cu126"}

# macOS (Apple Silicon): CPU wheels (PyPI has arm64 wheels)
[target.osx-arm64.pypi-dependencies]
torch = "==2.5.1"
