defaults:
  - swiglu_dense_template
  - _self_

common:
  _target_: src.definitions.Common
  dmodel: 768
  dff: 1920
  datt: 768
  n_blocks: 12
  q_heads: 12
  kv_heads: 12
  vocab_size: 50304
  sequence_length: 256
  head_norm: true
  init_scale: 0.1
  init_type: truncated_normal_fixed
  model_type: gpt