defaults:
  - ../_cluster@_here_: entropy
  - ../_model@_here_: plasticity_test
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: c4
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default

common:
  sequence_length: 512
  batch_size: 512

trainer:
  gradient_accumulation_steps: 1
  n_steps: 10_000
  ^learning_rate: [2e-4, 5e-4, 1e-3, 2e-3]

infrastructure:
  metric_logger:
    tags:
      - nano
      - plasticity
      - scheduler_comparison

  slurm:
    gres: gpu:2
    time: "02:00:00"
