defaults:
  - base_scheduler_comparison

trainer:
  n_steps: 11_000
  scheduler:
    _partial_: true
    _target_: src.plasticity.schedulers.RepeatedScheduler
    n_steps: ${trainer.n_steps}
    num_cycles: 3
    warmup_fraction: 0.01
    base_scheduler_factory:
      _partial_: true
      _target_: src.plasticity.schedulers.CosineScheduler
      final_lr_fraction: 0.1

infrastructure:
  metric_logger:
    name: Plasticity_Repeated_Long_Cosine
