defaults:
  - base_scheduler_comparison

trainer:
  scheduler:
    _partial_: true
    _target_: src.plasticity.schedulers.WSDScheduler
    warmup_steps: ${eval:'int(${trainer.n_steps} * 0.01)'}
    stable_steps: ${eval:'int(${trainer.n_steps} * 0.89)'}
    decay_steps: ${eval:'int(${trainer.n_steps} * 0.1)'}
    final_lr_fraction: 0.1

infrastructure:
  metric_logger:
    name: Plasticity_Standard_WSD
