defaults:
  - base_scheduler_comparison

trainer:
  scheduler:
    _partial_: true
    _target_: src.plasticity.schedulers.CosineScheduler
    final_lr_fraction: 0.1
    n_steps: ${trainer.n_steps}

infrastructure:
  metric_logger:
    name: Plasticity_Standard_Cosine
