defaults:
  - _cluster@_here_: entropy
  - _model@_here_: plasticity_test
  - _trainer@_here_: llama
  - _dataset@_here_: c4
  - _checkpoints@_here_: none
  - _misc@_here_: default

hydra:
  searchpath:
    - file://configs

common:
  sequence_length: 256
  batch_size: 256

trainer:
  gradient_accumulation_steps: 1
  n_steps: 1000
  learning_rate: 1e-3

  checkpoint:
    save:
      path: checkpoint

infrastructure:
  metric_logger:
    name: Plasticity_Test
    tags:
      - nano
      - plasticity
      - test

  slurm:
    gres: gpu:4
    time: "01:00:00"
