infrastructure:
  server: entropy
  max_concurrent_jobs: null
  slurm:
    cpus_per_gpu: 16
    gres: ???
    job-name: test
    mem_per_gpu: 125G
    nodes: 1
    partition: a100
    time: "2-00:00:00"

  script:
    - "PROJECT_HOME_PATH=/storage_nvme_2/projected_compression"
    - |
      VENV_PATH=$PROJECT_HOME_PATH/pc_venv
      export HF_HOME=$PROJECT_HOME_PATH/hf_cache

      # Check if venv exists
      if [ ! -d "$VENV_PATH" ]; then
        echo 'Virtual environment not found. Creating...'
        python3 -m venv "$VENV_PATH"
        pip install --upgrade pip
      fi 
      source "$VENV_PATH/bin/activate"
      pip install --upgrade -r requirements.txt

cluster_switch:
  train_path_c4: "/storage_nvme_1/llm-random/datasets/c4/train"
  eval_path_c4: "/storage_nvme_1/llm-random/datasets/c4/validation"
  train_path_fineweb: null
  eval_path_fineweb: null
