infrastructure:
  server: writer
  slurm:
    cpus_per_gpu: 16
    gres: ???
    job-name: test
    mem_per_gpu: 125G
    nodes: 1
    partition: debug
    time: "2-00:00:00"

  script:
    - 'export PROJECT_HOME_PATH=/home/ubuntu/llm-random-group/nano'
    - 'export HF_HOME=$PROJECT_HOME_PATH/hf_cache'

    # hydra errors
    - 'export HYDRA_FULL_ERROR=1'

    # export pixi variables
    - 'export PIXI_HOME=/home/ubuntu/llm-random-group/nano/pixi'
    - 'export PATH="$PIXI_HOME/bin:$PATH"'
    - 'export XDG_DATA_HOME="$PIXI_HOME/data"'
    - 'export XDG_CACHE_HOME="$PIXI_HOME/cache"'
    - 'export XDG_STATE_HOME="$PIXI_HOME/state"'
    
    # activate pixi
    - 'cd "$PIXI_HOME"'
    - 'eval "$(pixi shell-hook)"'
    - 'cd -'

cluster_switch:
  train_path_c4: "/home/ubuntu/llm-random-group/datasets/c4_train"
  eval_path_c4: "/home/ubuntu/llm-random-group/datasets/c4_validation"
  train_path_fineweb: null
  eval_path_fineweb: null
