defaults:
  - ../_cluster@_here_: entropy
  - ../_model/smollm@_here_: def_1700
  - ../_trainer@_here_: llama
  - ../_dataset@_here_: fineweb
  - ../_checkpoints@_here_: none
  - ../_misc@_here_: default


common:
  sequence_length: 1024
  batch_size: 512

  # target_dmodel: 448 # 10
  # target_dff: 1728
  # target_dmodel: 960 # 30
  # target_dff: 3840
  target_dmodel: 1344 # 50
  target_dff: 5376
  # target_dmodel: 1728 # 75
  # target_dff: 6912


trainer:
  gradient_accumulation_steps: 16
  ^n_steps: 
    - 2048 # 1B tokens
    # - 4096
    # - 6144
    # - 8192
    # - 12288
    # - 16384

  # learning_rate: ??? # CHANGE # 10
  # learning_rate: ??? # CHANGE # 30
  learning_rate: ??? # CHANGE # 50

  scheduler:
    warmup_steps: 80

  checkpoint:
   load:
    type: huggingface
    path: "HuggingFaceTB/SmolLM-1.7B"
   save:
    type: nano
    path: ??? # CHANGE

  train_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B

  eval_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B


infrastructure:
  metric_logger:
    name: SLLM_1700_prune
    tags:
      - nano
      - pc
      - smollm_1700
      - hard_pruning
      - 50p
      # - 30p
      # - 10p
      # - 35p
      # - 20p

  slurm: 
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4
    time: "0-12:00:00"


apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    dimensions_importances_path: ??? # CHANGE
    target_dmodel: ${common.target_dmodel}
    target_dff: ${common.target_dff}