
defaults:
  - llama_distillation

common_distillation:
  dmodel: 2048
  dff: 8192
  datt: 2048
  n_blocks: 16
  q_heads: 32
  kv_heads: 8
  vocab_size: 128256

distillation:
  load:
    path: "meta-llama/Llama-3.2-1B"
    