
infrastructure:
  metric_logger:
    project_name: pmtest/llm-random
    heavy_metrics_calculation_interval: 100
    new_neptune_job: true
    new_wandb_job: true
    type: neptune
    name: default
    tags:
      - nano

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git

  generated_configs_path: generated_configs

  cemetery_experiments_dir: "~/llmrandom_cemetery"

evaluator: null