
infrastructure:
  metric_logger:
    project_name: pmtest/llm-random
    heavy_metrics_calculation_interval: 100
    new_neptune_job: true
    new_wandb_job: true
    type: neptune
    name: default
    tags:
      - nano

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git

  generated_configs_path: generated_configs

  cemetery_experiments_dir: "~/llmrandom_cemetery"

trainer:
  checkpoint:
    save:
      type: nano
      interval: -1
      path: null
      model_checkpoint_filename: __model_checkpoint_filename.pt
      training_state_filename: __training_state_filename.pt

    load:
      type: nano
      path: null
      model_checkpoint_filename: __model_checkpoint_filename.pt
      training_state_filename: null # not tested
      only_weights: true # false not tested

evaluator: null