defaults:
  - base_pc_mem_eff
  - _self_

common:
  dmodel: 1344 # 50% parameter compression
  dff: 5376 # 50% parameter compression
  dhead: 64
  sequence_length: 512
  base_dmodel: 2048
  base_dff: 8192
  n_blocks: 16
  q_heads: 32
  kv_heads: 8