defaults:
  - ../../_misc@_here_: default
  - ../../_cluster@_here_: helios
  - ../../_model/llama@_here_: 1B
  - _self_


trainer:
  checkpoint:
    load:
      type: huggingface
      path: "meta-llama/Llama-3.2-1B"

    save:
      path: ??? # CHANGE ME

infrastructure:
  metric_logger:
    name: PC_save_pretrained_hf_to_nano
    tags:
      - nano
      - pc
      - save_pretrained

init_model_opt_sched_fn: 
  _target_: src.core.llama.save_pretrained_llama_as_nano
  _partial_: true